services:
  app:
    build: .
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      - DATABASE_URL=mongodb://mongo:27017/armagedon
      - PAYLOAD_SECRET=${PAYLOAD_SECRET}
      - NODE_ENV=production
    volumes:
      - uploads_media:/app/media
      - uploads_gallery:/app/gallery-photos
      - uploads_audio:/app/audio-tracks
      - uploads_timetable:/app/timetable

  mongo:
    image: mongo:7
    restart: always
    volumes:
      - mongodata:/data/db
    command: --storageEngine=wiredTiger

volumes:
  mongodata:
  uploads_media:
  uploads_gallery:
  uploads_audio:
  uploads_timetable:
